# Generated by Django 4.2.9 on 2024-02-16 18:43

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='project_images/'),
        ),
    ]
