# Generated by Django 4.1 on 2024-08-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.FileField(upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='pitch',
            field=models.FileField(upload_to='pitches'),
        ),
    ]
