# Generated by Django 4.1 on 2024-08-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0002_alter_empresas_logo_alter_empresas_pitch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='tempo_existencia',
            new_name='TEMPO_EXISTENCIA_CHOICES',
        ),
    ]
