# Generated by Django 4.1 on 2024-08-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0003_rename_tempo_existencia_empresas_tempo_existencia_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='TEMPO_EXISTENCIA_CHOICES',
            new_name='tempo_existencia',
        ),
    ]
